### ISSUE TITLE
FreDF在代码中的什么部分呢

### ISSUE THREAD

**Issue by Uncle-George-13** [Master-PLC/FreDF#1]
在您的时间序列分析库中没找到FreDF的用法啊

**Comment by Master-PLC** [comment]
FreDF主要通过各个exp中定义的auxiliary loss实现，其中auxi_lambda控制该损失的强度。具体可参考[exp/exp_long_term_forecasting.py](https://github.com/Master-PLC/FreDF/blob/main/exp/exp_long_term_forecasting.py)的179-222行。实验代码可参考[scripts/fredf_exp](https://github.com/Master-PLC/FreDF/tree/main/scripts/fredf_exp)

**Comment by Uncle-George-13** [comment]
您好，我看了您知乎上分享的文章，我如果想应用进来的话，是需要在计算损失那里进行修改嘛，我的损失函数是MSE损失

**Comment by HowardZJU** [comment]
是的，可以直接使用我们的对应损失
