### ISSUE TITLE
关于模型训练速度

### ISSUE THREAD

**Issue by Ycy21253728** [Master-PLC/FreDF#2]
作者大大您好，我加载了自己的数据集，数据量在2800个左右，采用单变量预测，使用的是autofomer,只修改了batchsize为128，学习率为0.001，其他超参数设置没有更改。模型训练的速度很慢，一个epoch跑了40秒，请问有哪里可以改进吗？

**Comment by minaas2** [comment]
学习了这个代码以后，这个repo的基础模型是对准TSLibrary这个库的实现的（readme里好像也说了）。

主要修改的地方好像就是exp里面的损失函数，这个好像算起来不怎么花时间（我本地的环境是单卡4090）。

所以autoformer的速度问题，可能去TSLib那边更能得到帮助？

**Comment by Ycy21253728** [comment]
您好。请问您跑的是自己的数据集吗，我在TSLib跑自己的数据集，训练速度都挺快的。

**Comment by Master-PLC** [comment]
@minaas2 您的理解是正确的，我们主要是基于TSLibrary库实现的。
@Ycy21253728 除了损失函数的差异，还有一点是我们的库中使用了torchmetrics，在GPU上计算指标替代了原先将tensor卸载到cpu上通过sklean的函数计算指标的方式。您可以还原尝试一下速率的差异

**Comment by Ycy21253728** [comment]
@Master-PLC 作者大大您好，在train的时候就发现速度较慢，看代码，指标计算应该是在test里面。请问可能有其他因素吗，您在训练几个公共数据集时，速度怎么样。

**Comment by Master-PLC** [comment]
训练速度主要看模型容量、数据集大小、数据维度以及pred_len吧，像是Autoformer、PatchTST这些模型通常都比较慢，想DLinear都挺快的，然后数据集的话ECL、Weather可能慢点，其他数据集都比较小还挺快的。

**Comment by Ycy21253728** [comment]
好的，感谢您的耐心回复
