### ISSUE TITLE
关于结果

### ISSUE THREAD

**Issue by WangXinTong1202** [Master-PLC/FreDF#7]
您好，我在patchtst中应用了您的损失函数(rrt, mag-phase, α=1/0.8），模型很快就earlystop且mse比不使用fredf增加了0.5左右。请问是因为数据集(频域loss大小接近时域loss的10倍)或者模型(svd去噪+TCN+patchtst)不适合这个损失函数吗? 希望您能给一些建议，谢谢

**Comment by HowardZJU** [comment]
Hi，目前在我们实验覆盖的模型集合中，基本没有出现很快earlystop的情况，且对DLinear模型、Transformer类模型，FreDF带来的收益都是比较明显的（见arxiv版本的最后几张灵敏度图）

在某些数据集上，如果频域loss大小接近时域loss的10倍，推测：可能不仅需要调节alpha，也需要调节lr，抵消loss量级的变化带来的不稳定性。

在arxiv论文中，patchtst目前不在我们涵盖的model list里，也没有放出对应的结果（因为这个模型input sequence length和我们依赖的TSLIB的96对不齐）。不过我们最近也跑了一下fredf+patchtst的效果，还是有一些收益的（注意input sequence length不能设为96，否则patchtst效果本身就很差）。但是“svd去噪+TCN+patchtst”，目前没有见到这个模型，所以很难给出具体建议。
